// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQhEJmV7LIa2REsByP-kBThRYP5SHxHYE',
    appId: '1:666347764447:web:8e0f6dd19db13b08d2476a',
    messagingSenderId: '666347764447',
    projectId: 'inspius-todo',
    authDomain: 'inspius-todo.firebaseapp.com',
    storageBucket: 'inspius-todo.appspot.com',
    measurementId: 'G-D6QTRYP182',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDASqlos_iuTKvosiseAQqATe18_LWWFUQ',
    appId: '1:666347764447:android:6985a78587fab9f0d2476a',
    messagingSenderId: '666347764447',
    projectId: 'inspius-todo',
    storageBucket: 'inspius-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN7qskZko4xRl8hgXXZhUQZxYr8IidfOA',
    appId: '1:666347764447:ios:e0877557617bcc54d2476a',
    messagingSenderId: '666347764447',
    projectId: 'inspius-todo',
    storageBucket: 'inspius-todo.appspot.com',
    iosClientId: '666347764447-lrrnugbkiobgi3vpc8nk1mu1jp2581ld.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN7qskZko4xRl8hgXXZhUQZxYr8IidfOA',
    appId: '1:666347764447:ios:e0877557617bcc54d2476a',
    messagingSenderId: '666347764447',
    projectId: 'inspius-todo',
    storageBucket: 'inspius-todo.appspot.com',
    iosClientId: '666347764447-lrrnugbkiobgi3vpc8nk1mu1jp2581ld.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFirestore',
  );
}
